"""
deepguard/detectors/metadata_detector.py
──────────────────────────────────────────
Layer 1 Forensics: Cryptographic Metadata (C2PA)

Checks images for Coalition for Content Provenance and Authenticity (C2PA)
signatures. Many modern generative AI models (OpenAI DALL-E 3, Adobe Firefly,
Microsoft Designer) embed these signatures.

If a valid C2PA manifest explicitly states the image was generated by an AI
software agent, we have 100% cryptographic proof it is a deepfake/synthetic.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

try:
    import c2pa
    HAS_C2PA = True
except ImportError:
    HAS_C2PA = False

logger = logging.getLogger(__name__)

# Common AI generators found in C2PA softwareAgent strings
_AI_AGENTS = {
    "dall-e", "midjourney", "firefly", "stable diffusion", "flux",
    "bing image creator", "microsoft designer", "openai", "meta ai"
}

class MetadataResult:
    def __init__(self, is_ai_generated: bool, confidence: float, evidence: str | None = None):
        self.is_ai_generated = is_ai_generated
        self.confidence = confidence
        self.evidence = evidence

def check_c2pa(image_path: Path) -> MetadataResult | None:
    """
    Check the image for C2PA cryptographic metadata indicating AI generation.

    Returns:
        MetadataResult if a clear AI signature is found.
        None if no C2PA data is present or it doesn't indicate AI.
    """
    if not HAS_C2PA:
        logger.warning("c2pa-python not installed. Skipping cryptographic metadata check.")
        return None

    try:
        # reader expects format string ("image/jpeg", "image/png", etc)
        fmt = f"image/{image_path.suffix.lstrip('.').lower()}"
        if fmt == "image/jpg":
            fmt = "image/jpeg"

        with open(image_path, "rb") as f:
            reader = c2pa.Reader(fmt, f)
            manifest_json = reader.json()

            if not manifest_json:
                return None

            manifest_data = json.loads(manifest_json)
            active_manifest_id = manifest_data.get("active_manifest")
            if not active_manifest_id:
                return None

            active_manifest = manifest_data.get("manifests", {}).get(active_manifest_id, {})
            assertions = active_manifest.get("assertions", [])

            for assertion in assertions:
                # Check for action assertions
                if assertion.get("label") == "c2pa.actions":
                    actions = assertion.get("data", {}).get("actions", [])
                    for action in actions:
                        # Sometimes 'c2pa.created' or 'c2pa.generated' indicates the source
                        agent = action.get("softwareAgent", "").lower()

                        # Direct string matching against known AI tools
                        for ai_tool in _AI_AGENTS:
                            if ai_tool in agent:
                                logger.info("C2PA Match: Image generated by %s", agent)
                                return MetadataResult(
                                    is_ai_generated=True,
                                    confidence=1.0,
                                    evidence=f"Cryptographic C2PA signature found: {agent}"
                                )

                        # Check action type
                        action_type = action.get("action", "")
                        if "trained_algorithmic_media" in action_type or "generated" in action_type:
                            logger.info("C2PA Match: Algorithmic media action detected.")
                            return MetadataResult(
                                is_ai_generated=True,
                                confidence=1.0,
                                evidence=f"C2PA action indicates generation: {action_type}"
                            )

    except Exception as e:
        logger.debug("C2PA check failed or no metadata found for %s: %s", image_path.name, e)

    return None
